version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: waveguard-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD", "bash", "-c", "echo ruok | nc localhost 2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: waveguard-kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
      # - "29092:29092"  # Port pour les connexions internes (Docker)
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 15s
      timeout: 10s
      retries: 5

  spark-master:
    image: apache/spark:3.4.0
    container_name: waveguard-spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"   # Spark Web UI
      - "7077:7077"   # Spark Master port
    environment:
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 8080

    volumes:
       - ./jobs:/opt/spark/jobs
       - ./checkpoint:/tmp/waveguard_checkpoint
       - ./datalake:/tmp/waveguard_lake

  spark-worker:
    image: apache/spark:3.4.0
    container_name: waveguard-spark-worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      # - "8081:8081"   # Worker Web UI
      - "8082:8082"
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      # SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_WORKER_WEBUI_PORT: 8082
    volumes:
      - ./jobs:/opt/spark/jobs           # dépôt des scripts Python
      - ./checkpoint:/tmp/waveguard_checkpoint
      - ./datalake:/tmp/waveguard_lake

  grafana:
    image: grafana/grafana:10.4.0
    container_name: waveguard-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: waveguard
    volumes:
      - grafana_data:/var/lib/grafana

  airflow:
    image: apache/airflow:2.9.0
    container_name: waveguard-airflow
    ports:
      # - "8082:8080"
      - "8081:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor 
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
    volumes:
      - ./dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
    command: >
      bash -c "airflow db init &&
               airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email admin@ept.sn &&
               (airflow webserver & airflow scheduler)"

volumes:
  grafana_data:
  airflow_logs: